# zmodload zsh/zprof

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export TZ="Asia/Jakarta"

# Theme
ZSH_THEME=""

# Oh My Zsh
zstyle ':omz:update' mode auto  # disabled|auto|reminder
zstyle ':omz:update' frequency 3

# ZSH Cache
ZSH_COMPDUMP="$ZSH/cache/completions/.zcompdump-${HOST/.*/}-${ZSH_VERSION}"

# Disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

# Zoxide
ZOXIDE_CMD_OVERRIDE="cd"

plugins=(
	git
	direnv
	starship
	bun
	aws
	httpie
	zsh-autosuggestions
	zsh-syntax-highlighting
	fast-syntax-highlighting
	zsh-autocomplete
	zoxide
)

# LS Colors
export CLICOLOR="1"
export LSCOLORS="ExFxBxDxCxegedabagacad"

# VirtualEnv
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Source Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Source Functions
if [ -f $HOME/.functions ]; then
	source $HOME/.functions
fi

# Rust
if [ -f $HOME/.cargo/env ]; then
	source $HOME/.cargo/env
fi

# Aliases
alias c="cursor"
alias ll="ls -lhA"
alias nix_switch="sudo darwin-rebuild switch --flake ~/config/nix#setup"
alias nix_update="nix flake update --flake ~/config/nix"
alias speed="speedtest -u auto-decimal-bytes"
alias update="brew update && omz update"
alias upgrade="brew upgrade && brew cleanup"

# Functions
clean() {
	# TODO: Add more cleaning options
	brew cleanup -s --prune=1
	uv cache prune
	pnpm store prune
	bun pm cache rm -g
	npm cache clean --force
	yarn cache clean --all
	sudo zsh -c "nix-collect-garbage -d"
}

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# Bun
export PATH="/Users/asoka/.bun/bin:$PATH"

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

# Android Studio
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# UV
export PATH="/Users/asoka/.local/bin:$PATH"

# OpenCode
source $HOME/.config/opencode/flags.zsh
