# zmodload zsh/zprof

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export TZ="Asia/Jakarta"

# Theme
ZSH_THEME=""

# Oh My Zsh
zstyle ':omz:update' mode auto  # disabled|auto|reminder
zstyle ':omz:update' frequency 3

# ZSH Cache
ZSH_COMPDUMP="$ZSH/cache/completions/.zcompdump-${HOST/.*/}-${ZSH_VERSION}"

# Disable auto-setting terminal title
DISABLE_AUTO_TITLE="true"

# Zoxide
ZOXIDE_CMD_OVERRIDE="cd"

plugins=(
	git
	direnv
	starship
	bun
	aws
	httpie
	zsh-autosuggestions
	zsh-syntax-highlighting
	fast-syntax-highlighting
	zsh-autocomplete
	zoxide
)

# LS Colors
export CLICOLOR="1"
export LSCOLORS="ExFxBxDxCxegedabagacad"

# VirtualEnv
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Source Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Source Functions
if [ -f $HOME/.functions ]; then
	source $HOME/.functions
fi

# Rust
if [ -f $HOME/.cargo/env ]; then
	source $HOME/.cargo/env
fi

# Aliases
alias c="cursor"
alias ll="ls -lhA"
alias nix_switch="sudo darwin-rebuild switch --flake ~/config/nix#setup"
alias nix_update="nix flake update --flake ~/config/nix"
alias speed="speedtest -u auto-decimal-bytes"
alias update="brew update && omz update"
alias upgrade="brew upgrade && brew cleanup"

# Functions
clean() {
	# TODO: Add more cleaning options
	brew cleanup -s --prune=1
	uv cache prune
	pnpm store prune
	bun pm cache rm -g
	npm cache clean --force
	yarn cache clean --all
	sudo zsh -c "nix-collect-garbage -d"
}

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

#compdef pnpm
###-begin-pnpm-completion-###
if type compdef &>/dev/null; then
  _pnpm_completion () {
    # Function to format completions
    format_completions() {
      local -a formatted=()
      local item desc
      
      for item in $@; do        
        # Handle items with existing descriptions (containing --)
        if [[ $item == *--* ]]; then
          formatted+=("\\${item}")
        else
          formatted+=("${item}")
        fi
      done
      
      # Sort and return formatted items
      print -l "${(i)formatted[@]}"
    }

    complete_options_or_commands() {
      local current_word="${words[CURRENT]}"

      local stop_parse_string="--"
      local stop_parse_index=$words[(Ie)$stop_parse_string]

      local -a formatted
   	  local formatted=($(format_completions "${reply[@]}"))
      local type

      # Skip if the last word is --, e.g. "pnpm test -- <something can't complete>"
      if [[ $stop_parse_index != 0 && $CURRENT > stop_parse_index ]]; then
        return
      fi

      if [[ $current_word == -* ]]; then
        type="options"
      else
        type="commands"
      fi

      _describe $type formatted
    }

    local reply
    local si=$IFS

    IFS=$'\n' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" SHELL=zsh pnpm completion-server -- "${words[@]}"))
    IFS=$si

    if [ "$reply" = "__tabtab_complete_files__" ]; then
      _files
    else
      complete_options_or_commands
    fi
  }
  # When called by the Zsh completion system, this will end with
  # "loadautofunc" when initially autoloaded and "shfunc" later on, otherwise,
  # the script was "eval"-ed so use "compdef" to register it with the
  # completion system
  if [[ $zsh_eval_context == *func ]]; then
    _pnpm_completion "$@"
  else
    compdef _pnpm_completion pnpm
  fi
fi
###-end-pnpm-completion-###

# Bun
export PATH="/Users/asoka/.bun/bin:$PATH"

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home

# Android Studio
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# UV
export PATH="/Users/asoka/.local/bin:$PATH"

# OpenCode
source $HOME/.config/opencode/flags.zsh
source $HOME/.pi/flags.zsh
