export const ICONS = {
  answered: "●",
  unanswered: "○",
  confirm: "✓",
  customAnswer: "✎",
  optionAnswer: "•",
  warning: "!",
  cursor: "❯",
  previousTabs: "‹",
  nextTabs: "›",
  singleSelected: "●",
  singleUnselected: "○",
  multipleSelected: "[x]",
  multipleUnselected: "[ ]",
  success: "✓",
  dismissed: "✗",
  left: "←",
  horizontal: "←→",
  separator: "•",
} as const;
